server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/advice_db
    username: postgres
    password: admin1234   #Contraseña Cosette
    #password: jose       #Contraseña Jose
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
